[package]
name = "pda"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
solana-program = "1.10.9"
borsh = "0.9.3"

[dev-dependencies]
solana-program-test = "1.10.9"
solana-sdk = "1.10.9"

[lib]
crate-type = ["cdylib", "lib"]